# Generated by Django 2.0.2 on 2018-02-19 12:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0001_initial'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alternate_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHandicap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_handicap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_handicap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Week')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Week')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Hole')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.PlayerRound')),
            ],
        ),
    ]
