# Generated by Django 2.0.2 on 2018-02-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerscores',
            unique_together={('round', 'hole')},
        ),
    ]
