# Generated by Django 2.0.2 on 2018-02-19 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonsettings',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Season', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('division', 'year')},
        ),
    ]
