# Generated by Django 2.0.2 on 2018-02-19 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20180219_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonsettings',
            name='season',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league.Season'),
        ),
    ]
