# Generated by Django 2.0.2 on 2018-02-19 12:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(18)])),
                ('override', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('points_ind', models.BooleanField()),
                ('best_ball_ind', models.BooleanField()),
                ('alternate_id', models.IntegerField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Season')),
            ],
        ),
        migrations.CreateModel(
            name='TeamScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('nine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Nine')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Season')),
            ],
        ),
        migrations.AddField(
            model_name='teamscore',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Week'),
        ),
        migrations.AddField(
            model_name='matchpoints',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Team'),
        ),
        migrations.AddField(
            model_name='matchpoints',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Week'),
        ),
        migrations.AddField(
            model_name='match',
            name='first_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='match.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='second_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='match.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='starting_hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Hole'),
        ),
        migrations.AddField(
            model_name='match',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Week'),
        ),
    ]
