# Generated by Django 2.0.2 on 2018-02-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('week', 'second_team'), ('week', 'first_team')},
        ),
        migrations.AlterUniqueTogether(
            name='matchpoints',
            unique_together={('team', 'week')},
        ),
        migrations.AlterUniqueTogether(
            name='teamscore',
            unique_together={('team', 'week')},
        ),
        migrations.AlterUniqueTogether(
            name='week',
            unique_together={('season', 'number')},
        ),
    ]
